server.port=8093

spring.datasource.url=jdbc:postgresql://postgres-db:5432/transaction_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.data.redis.host=redis
spring.data.redis.port=6379

# transaction-service가 호출하는 동료 서비스 주소 (Docker Compose 서비스명 DNS)
services.account-service.url=http://account-service:8091
services.tokenization-service.url=http://tokenization-service:8092
